### ISSUE TITLE
tcosproject wiki not working

### ISSUE THREAD

**Issue by nicopace** [mariodebian/tcos#3]
The content is not being shown:
wiki.tcosproject.org/Main_Page

**Comment by mariodebian** [comment]
TCOS project is officially dead, and have not renewed the domain name

**Comment by nicopace** [comment]
What a pitty Mario... and what happened with the codebase? (i guess it became outdated).
What would you recommend to use instead?

Thanks for all the hard work you did for this project! It was an amazing tool!!!
